<a href="https://colab.research.google.com/github/Lio72rga/Mineria-de-Datos-2026/blob/main/Notebook3_Modelos_con_TensorFlow_LM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. Notebook Modelos con TensorFlow

Centro Politécnico Superior Malvinas Argentinas  
**Tecnicatura en Ciencias de Datos e Inteligencia Artificial**  
Clase 10 – Minería de Texto con TensorFlow y Scikit‑learn  
Autor: Lionel Martínez  
Fecha: Junio 2026


## -- Introducción --

**Objetivo:** Implementar un modelo de red neuronal con TensorFlow para clasificar opiniones en texto como positivas o negativas.  
**Dataset:** Opiniones simuladas en español sobre productos.  

En esta actividad se abordarán los pasos fundamentales:  
1. Tokenización y vectorización del texto.  
2. Aplicación de padding para uniformar longitudes.  
3. Construcción de un modelo secuencial con capas Embedding y LSTM.  
4. Entrenamiento y evaluación del modelo.  

El resultado será un clasificador binario capaz de distinguir entre opiniones positivas y negativas.


## Importación de librerías

In [1]:
# Instalar TensorFlow (solo necesario en entornos virtuales o locales)
!pip install tensorflow

# Importación de librerías
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np


## Datos de ejemplo

In [2]:
# Opiniones de ejemplo
textos = [
    "Me encanta este producto",
    "Es un desastre, muy malo",
    "Excelente calidad y buen precio",
    "No me gustó, fue horrible"
]

# Etiquetas: 1 = Positivo, 0 = Negativo
etiquetas = np.array([1, 0, 1, 0])


## Tokenización y Padding

In [3]:
# Tokenización del texto
tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(textos)
sequences = tokenizer.texts_to_sequences(textos)

# Padding para uniformar longitudes
padded_sequences = pad_sequences(sequences, maxlen=5, padding='post')

print("Secuencias tokenizadas y padded:\n", padded_sequences)


Secuencias tokenizadas y padded:
 [[ 2  3  4  5  0]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16  2 17 18 19]]


## Definición del Modelo

In [4]:
# Definir el modelo de red neuronal
modelo = keras.Sequential([
    Embedding(input_dim=1000, output_dim=16, input_length=5),
    LSTM(16),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compilar el modelo
modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## Entrenamiento y Evaluación

In [5]:
# Entrenar el modelo
historial = modelo.fit(padded_sequences, etiquetas, epochs=5, verbose=1)

# Evaluar el modelo
loss, accuracy = modelo.evaluate(padded_sequences, etiquetas, verbose=0)
print(f"Precisión del modelo: {accuracy:.2f}")


Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.7500 - loss: 0.6908
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.6890
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.6876
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6860
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.6846
Precisión del modelo: 1.00


### Explicación del Código
- Se tokenizan las opiniones y se convierten en secuencias numéricas.  
- Se aplica padding para que todas las secuencias tengan la misma longitud.  
- El modelo incluye una capa Embedding para representar palabras, seguida de una LSTM para aprender patrones en secuencias.  
- Se entrena el modelo con clasificación binaria (positivo/negativo).  
- La precisión indica el desempeño del clasificador en los datos de ejemplo.


## -- Conclusión --

TensorFlow permite construir modelos de redes neuronales capaces de capturar relaciones complejas en texto.  
Aunque este ejemplo es pequeño, la misma arquitectura puede escalarse a conjuntos de datos más grandes y tareas avanzadas como análisis de sentimientos o chatbots.
